shared-secret = "cHaNgE0mE1=="
bind-address = "localhost"
bind-port = 20211

[keepalived]
virtual-router-id-base = 4
interface = "enp1"

[keepalived.service]
config-file = "keepalived.conf"
reload-command = ["echo", "reloading keepalived"]
start-command = ["echo", "starting keepalived"]
status-command = ["echo", "checking keepalived"]

[nftables.service]
config-file = "nftables.conf"
reload-command = ["echo", "reloading nftables"]
start-command = ["echo", "starting nftables"]
status-command = ["echo", "checking nftables"]
